name: Test
on: [] # pull_request, push, workflow_dispatch

jobs:
  test:
    runs-on: self-hosted
    container:
      image: debian:latest
      ports:
        - 80
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
      - run: